### ISSUE TITLE
Crashes whenever I try exporting with QC open @ the same time

### ISSUE THREAD

**Issue by krishpop** [tarngerine/sketch-origami-export#3]
Sketch Version 3.2.2

Is this a known/common issue for other people? I really want to be able to use this plugin, but if I can't, what is the easiest way for me to import screens into Origami on my own?

**Comment by tarngerine** [comment]
Have you updated to the latest plugin since last week? I recently fixed a bug where any symbols with groups inside would crash.

**Comment by franceindia** [comment]
I've got the latest everything but it's still crashing.  I even tried taking groups out of symbols but no luck.  I'd be happy to share what I'm doing with you in a private message if it helps.

**Comment by franceindia** [comment]
Ok, I got a reply from Sketch saying they're releasing an update tomorrow that should fix this.

**Comment by tarngerine** [comment]
Oh could you link me to their response? I'm curious what the issue was! Thanks for reporting
