### ISSUE TITLE
How to change the export scale? 

### ISSUE THREAD

**Issue by mynameispj** [tarngerine/sketch-origami-export#4]
Hi! Thanks for all your work on this plugin. Quick question: when the plugin first prompted me to select the export scale, I chose the wrong scale and need to change it. However, now whenever I export, I'm not prompted with the scale selection box, and I can't find a way to get the scale selection box to reappear. 

I've tried restarting Sketch and deleting and re-installing the plugin, and it seems to still be retaining my original (incorrect) selection. 

Could you please point me in the right direction? Thanks again! 

Best,
PJ

**Comment by tarngerine** [comment]
Hey PJ — the quickest way to fix this is just deleting the export folder. If Sketch detects there is an existing folder with the same filename it will not prompt for a new scale. If there is no existing folder, it will prompt.




Sorry for that confusion! Another way is to modify the data.json file inside the export folder manually, as that is where the scale is "saved"




Thanks,

Julius

**Comment by mynameispj** [comment]
Hey Julius, 

Thanks so much for the quick answer and the help! That worked like a charm. :) 

Really appreciate it! 

Best,
PJ
