### ISSUE TITLE
Getting a directory scanner instead of live images

### ISSUE THREAD

**Issue by gordonirving** [tarngerine/sketch-origami-export#5]
Drag and drop of the generated folder over Quartz Composer while pressing cmd + option creates a directory scanner instead of live images: http://cl.ly/image/3B0v2r3Z4246

I'm using Sketch 3.3 and, Quartz Composer 4.6, Origami 2.0.2 and OS 10.10.3.

Gordon

**Comment by tarngerine** [comment]
Yea I think the best solution for the mean time is to select all the
individual files (cmd a) and drag those in. This is a QC thing rather than
a sketch plugin thing but will figure out a better dolutjon !

**Comment by gordonirving** [comment]
Tried cmd + A but that only imports one asset at a time and doesn't keep the original position.

**Comment by tarngerine** [comment]
Oh yea so maintaining the original position is not released yet - sorry! We're working on it for a future release of origami. Check out the tutorial video https://vimeo.com/120452278
