### ISSUE TITLE
I don't have the option to scale the export

### ISSUE THREAD

**Issue by lucky13820** [tarngerine/sketch-origami-export#7]
Once I press the shortcut, it will just export the pngs without showing me screen to scale them. I can't get my pngs export scale to 2x, what should I do?

**Comment by tarngerine** [comment]
Hey Lucky!




We prompt for export scale per existing origamiblueprint. You aren't Getting prompted bc you've already seen the dialog once, right? 
If you show the exports folder (should be a command in plugin menu) you can either delete it and re run OR open the origamiblueprint folder there's a data.json you can edit with your text editor to change the scale.

**Comment by lucky13820** [comment]
Yes, that's right. I guess I just didn't pay a attention when the dialog showed up first. Thanks!
