### ISSUE TITLE
.5x export exporting to 5x

### ISSUE THREAD

**Issue by mdeblasio** [tarngerine/sketch-origami-export#8]
Export at 0.5x seems to be 5x 
Running OSX El Capitan  10.11 
other sizes work ok

**Comment by tarngerine** [comment]
this should be fixed! please redownload/reinstall :) sorry for the problem

**Comment by tarngerine** [comment]
https://github.com/tarngerine/sketch-origami-export/commit/e3e4ff525f1c1af771419bb05ac5288dcaa4bdd4
